### ISSUE TITLE
Make UpSet plot wider

### ISSUE THREAD

**Issue by berntpopp** [halbritter-lab/kidney-genetics#3]
The UpSet plot at https://halbritter-lab.github.io/kidney-genetics/analyses-plots.html#upset-plot-of-merged-analyses-sources is displayed very narrow and the numbers are not readable.
Adapt the plot to display nicer.

**Comment by ConstantinWolff** [comment]
We already did it once, but the plot is displayed quite narrow again. Make the plot wider and ensure that the changes are safed correctly.

- [ ] made plot wider
